FROM dart:3.2.6-sdk

WORKDIR /workspace/source

# install Flutter
RUN git clone --depth 1 --branch 3.16.9 https://github.com/flutter/flutter.git

CMD /workspace/source/flutter/bin/flutter pub get && cat pubspec.lock


