FROM dart:3.2.6-sdk
ENV FLUTTER_URL="https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.16.9-stable.tar.xz"

WORKDIR /workspace/source

RUN apt-get update
RUN apt-get install -y xz-utils

RUN git config --global --add safe.directory /workspace/source/flutter

RUN curl -o flutter.tar.xz $FLUTTER_URL
RUN tar xf flutter.tar.xz
RUN ls -l flutter/bin
RUN rm flutter.tar.xz
RUN flutter/bin/flutter pub get && cat pubspec.lock


